-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Dict.

module Dict.Abs where

import Prelude (Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Dictionary = Dict [Entry]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Entry = E Ident [Arg] | EA Ident [Arg] [Term]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Term = TermC Ident [Term] | TermA Arg
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Arg = NId Ident | NArg Integer | NStr String
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

